#pragma once

static const char *SLS_DASHBOARD_HTML = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SRT Live Server Console</title>
<style>
:root{--bg:#071019;--panel:#101d27;--panel2:#162735;--text:#e7f0f5;--muted:#8da4b4;--accent:#24d39a;--warn:#ffca62;--border:#203846}*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0,#113040 0,var(--bg) 42%);color:var(--text);font:14px/1.5 Inter,"Segoe UI",Arial,sans-serif}header,main{width:min(1240px,calc(100% - 40px));margin:0 auto}header{display:flex;justify-content:space-between;align-items:end;padding:34px 0 24px}h1{font-size:clamp(26px,4vw,38px);font-weight:600;margin:0;letter-spacing:-.04em}h2{font-size:17px;margin:0 0 16px}p{color:var(--muted);margin:6px 0 0}.pill{border:1px solid var(--border);border-radius:100px;padding:8px 14px;color:var(--muted);background:var(--panel)}.pill.live{border-color:#197c5d;color:var(--accent)}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;margin-bottom:16px}.card{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:20px}.controls{display:flex;flex-wrap:wrap;gap:10px;align-items:end}label{display:grid;gap:5px;color:var(--muted);font-size:12px}input,select,button{height:38px;border-radius:8px;border:1px solid var(--border);background:var(--panel2);color:var(--text);padding:0 12px;font:inherit}input[type=text]{min-width:188px}button{cursor:pointer;background:var(--accent);color:#042017;border:0;font-weight:600}button.ghost{background:var(--panel2);color:var(--text);border:1px solid var(--border)}.url{margin-top:14px;padding:12px;background:#07141c;border:1px solid var(--border);color:var(--accent);border-radius:8px;word-break:break-all;font-family:ui-monospace,monospace}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid var(--border);text-align:left;padding:12px 8px}th{color:var(--muted);font-weight:500;font-size:12px}tbody tr:last-child td{border-bottom:0}.empty{color:var(--muted);padding:30px 8px;text-align:center}.note{border-left:3px solid var(--warn)}code{color:var(--text)}#message{min-height:21px;color:var(--warn);margin-top:10px}@media(max-width:820px){.grid{grid-template-columns:1fr}header{display:block}header .pill{display:inline-block;margin-top:14px}.table-wrap{overflow-x:auto}}
</style></head><body>
<header><div><h1>SRT Live Server Console</h1><p>SRTLA-aware ingest and playback monitoring</p></div><span class="pill" id="health">Connecting</span></header>
<main><section class="grid"><div class="card"><h2>Connection Builder</h2><div class="controls">
<label>Server host<input id="host" type="text"></label><label>Role<select id="role"><option value="direct">Direct publish</option><option value="srtla">SRTLA publish</option><option value="play">Playback</option><option value="studio">Studio direct publish</option><option value="studio-play">Studio playback</option></select></label><label>Stream name<input id="stream" type="text" value="feed1"></label><button id="copy">Copy URL</button></div><div class="url" id="url"></div></div>
<div class="card"><h2>Stats Access</h2><div class="controls"><label>API key from <code>sls.conf</code><input id="key" type="password" placeholder="Authorization key"></label><button class="ghost" id="apply">Apply</button></div><div id="message">Configure <code>api_keys</code> to list all streams.</div></div></section>
<section class="card"><h2>Active Publishers</h2><div class="table-wrap"><table><thead><tr><th>Stream</th><th>Latency</th><th>RTT</th><th>Receive rate</th><th>Loss</th><th>Dropped</th><th>Receive buffer</th></tr></thead><tbody id="publishers"><tr><td class="empty" colspan="7">Waiting for statistics.</td></tr></tbody></table></div></section>
<section class="card note" style="margin-top:16px"><h2>Timing Scope</h2><p>SRT timestamp-based packet delivery (TSBPD) preserves timing and negotiated latency within each SRT connection. Equal configured latency helps keep receiver delay consistent, but it does not synchronize independently clocked cameras. Frame-aligned multi-camera production requires shared timecode/genlock or alignment in the receiving mixer.</p></section></main>
<script>
const $=id=>document.getElementById(id);const roles={direct:{port:4001,id:"publish/live/"},srtla:{port:4002,id:"publish/live/"},play:{port:4000,id:"play/live/"},studio:{port:30002,id:"publish/live/"},"studio-play":{port:30003,id:"play/live/"}};
$("host").value=location.hostname||"localhost";$("key").value=sessionStorage.getItem("sls-api-key")||"";
function buildUrl(){const role=roles[$("role").value],host=$("host").value.trim()||"localhost",stream=$("stream").value.trim()||"feed1";$("url").textContent=`srt://${host}:${role.port}?streamid=${role.id}${encodeURIComponent(stream)}`}
function number(value,suffix=""){return typeof value==="number"?`${value.toFixed(2)}${suffix}`:"-"}function escapeHtml(text){const span=document.createElement("span");span.textContent=text;return span.innerHTML}
async function refresh(){const headers={},key=$("key").value.trim();if(key)headers.Authorization=key;try{const response=await fetch("/stats",{headers}),data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);$("health").textContent="Online";$("health").classList.add("live");$("message").textContent="Statistics update every 2 seconds.";const publishers=Object.entries(data.publishers||{});$("publishers").innerHTML=publishers.length?publishers.map(([stream,s])=>`<tr><td>${escapeHtml(stream)}</td><td>${number(s.latency," ms")}</td><td>${number(s.rtt," ms")}</td><td>${number(s.mbpsRecvRate," Mbps")}</td><td>${s.pktRcvLoss??"-"}</td><td>${s.pktRcvDrop??"-"}</td><td>${number(s.msRcvBuf," ms")}</td></tr>`).join(""):'<tr><td class="empty" colspan="7">No active publishers.</td></tr>'}catch(error){$("health").textContent="Stats locked";$("health").classList.remove("live");$("message").textContent=error.message}}
["host","role","stream"].forEach(id=>$(id).addEventListener("input",buildUrl));$("copy").addEventListener("click",async()=>navigator.clipboard.writeText($("url").textContent));$("apply").addEventListener("click",()=>{sessionStorage.setItem("sls-api-key",$("key").value.trim());refresh()});buildUrl();refresh();setInterval(refresh,2000);
</script></body></html>)HTML";
