#pragma once

static const char *SLS_DASHBOARD_HTML = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SRT Live Server Console</title>
<style>
:root{--bg:#071019;--panel:#101d27;--panel2:#162735;--text:#e7f0f5;--muted:#8da4b4;--accent:#24d39a;--warn:#ffca62;--border:#203846}*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0,#113040 0,var(--bg) 42%);color:var(--text);font:14px/1.5 Inter,"Segoe UI",Arial,sans-serif}header,main{width:min(1240px,calc(100% - 40px));margin:0 auto}header{display:flex;justify-content:space-between;align-items:end;padding:34px 0 24px}h1{font-size:clamp(26px,4vw,38px);font-weight:600;margin:0;letter-spacing:-.04em}h2{font-size:17px;margin:0 0 16px}p{color:var(--muted);margin:6px 0 0}.pill{border:1px solid var(--border);border-radius:100px;padding:8px 14px;color:var(--muted);background:var(--panel)}.pill.live{border-color:#197c5d;color:var(--accent)}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;margin-bottom:16px}.card{border:1px solid var(--border);background:var(--panel);border-radius:14px;padding:20px}.controls{display:flex;flex-wrap:wrap;gap:10px;align-items:end}label{display:grid;gap:5px;color:var(--muted);font-size:12px}input,select,button{height:38px;border-radius:8px;border:1px solid var(--border);background:var(--panel2);color:var(--text);padding:0 12px;font:inherit}input[type=text]{min-width:188px}button{cursor:pointer;background:var(--accent);color:#042017;border:0;font-weight:600}button.ghost{background:var(--panel2);color:var(--text);border:1px solid var(--border)}.url{margin-top:14px;padding:12px;background:#07141c;border:1px solid var(--border);color:var(--accent);border-radius:8px;word-break:break-all;font-family:ui-monospace,monospace}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid var(--border);text-align:left;padding:12px 8px}th{color:var(--muted);font-weight:500;font-size:12px}tbody tr:last-child td{border-bottom:0}.empty{color:var(--muted);padding:30px 8px;text-align:center}.note{border-left:3px solid var(--warn)}code{color:var(--text)}#message{min-height:21px;color:var(--warn);margin-top:10px}@media(max-width:820px){.grid{grid-template-columns:1fr}header{display:block}header .pill{display:inline-block;margin-top:14px}.table-wrap{overflow-x:auto}}
.nav{display:flex;gap:10px;align-items:center}.nav a{height:38px;padding:8px 13px;border-radius:8px;border:1px solid var(--border);color:var(--text);text-decoration:none}.monitor{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.player{width:100%;min-height:260px;background:#03080c;border-radius:10px;margin-top:14px}.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.chart{background:#07141c;border:1px solid var(--border);border-radius:8px;padding:8px}.chart span{display:block;color:var(--muted);font-size:12px}.chart canvas{display:block;width:100%;height:104px}.capture{display:none;width:100%;margin-top:12px;border-radius:8px}.preview-message{color:var(--warn);min-height:22px;margin-top:8px}.clickable{cursor:pointer}.clickable:hover{background:var(--panel2)}
@media(max-width:900px){.monitor{grid-template-columns:1fr}.chart-grid{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>SRT Live Server Console</h1><p>SRTLA-aware ingest and playback monitoring</p></div><div class="nav"><a href="/help">Help</a><span class="pill" id="health">Connecting</span></div></header>
<main><section class="grid"><div class="card"><h2>Connection Builder</h2><div class="controls">
<label>Server host<input id="host" type="text"></label><label>Role<select id="role"><option value="direct">Direct publish</option><option value="srtla">SRTLA publish</option><option value="play">Playback</option><option value="studio">Studio direct publish</option><option value="studio-play">Studio playback</option></select></label><label>Stream name<input id="stream" type="text" value="feed1"></label><button id="copy">Copy URL</button></div><div class="url" id="url"></div></div>
<div class="card"><h2>Stats Access</h2><div class="controls"><label>API key from <code>sls.conf</code><input id="key" type="text" placeholder="Authorization key"></label><button class="ghost" id="apply">Apply</button></div><p>Bundled local-preview key: <code>sls-gui-dashboard-local</code>. Replace it before public exposure.</p><div id="message">Using the bundled dashboard key to list active streams.</div></div></section>
<section class="card"><h2>Active Publishers</h2><div class="table-wrap"><table><thead><tr><th>Stream</th><th>Latency</th><th>RTT</th><th>Receive rate</th><th>Loss</th><th>Dropped</th><th>Receive buffer</th></tr></thead><tbody id="publishers"><tr><td class="empty" colspan="7">Waiting for statistics.</td></tr></tbody></table></div></section>
<section class="monitor"><div class="card"><h2>Feed Monitor</h2><div class="controls"><label>Publisher type<select id="monitorRole"><option value="direct">Direct SRT (4001)</option><option value="srtla">SRTLA (4002)</option><option value="studio">Studio direct (30002)</option></select></label><label>Stream name<input id="monitorStream" type="text" value="feed1"></label><button id="loadPreview">Load Preview</button><button class="ghost" id="snapshot">Snapshot</button></div><div class="preview-message" id="previewMessage">Preview begins after the first completed HLS segments.</div><video class="player" id="video" controls playsinline></video><canvas class="capture" id="capture"></canvas><p>Video playback includes the source audio track. Use the player's mute and volume controls for audio monitoring.</p></div>
<div class="card"><h2>Connection History</h2><p>Rolling 60-second view for the selected stream. An API key is required only to list every publisher.</p><div class="chart-grid"><div class="chart"><span>Receive rate (Mbps)</span><canvas id="rateChart"></canvas></div><div class="chart"><span>RTT (ms)</span><canvas id="rttChart"></canvas></div><div class="chart"><span>Latency / buffer (ms)</span><canvas id="timingChart"></canvas></div><div class="chart"><span>Packet loss / drop</span><canvas id="packetChart"></canvas></div></div></div></section>
<section class="card note" style="margin-top:16px"><h2>Timing Scope</h2><p>SRT timestamp-based packet delivery (TSBPD) preserves timing and negotiated latency within each SRT connection. Equal configured latency helps keep receiver delay consistent, but it does not synchronize independently clocked cameras. Frame-aligned multi-camera production requires shared timecode/genlock or alignment in the receiving mixer.</p></section></main>
<script src="https://cdn.jsdelivr.net/npm/hls.js@1/dist/hls.min.js"></script>
<script>
const $=id=>document.getElementById(id);const roles={direct:{port:4001,id:"publish/live/"},srtla:{port:4002,id:"publish/live/"},play:{port:4000,id:"play/live/"},studio:{port:30002,id:"publish/live/"},"studio-play":{port:30003,id:"play/live/"}};
const history={rate:[],rtt:[],latency:[],buffer:[],loss:[],drop:[]};const bundledKey="sls-gui-dashboard-local";let hls=null;
$("host").value=location.hostname||"localhost";$("key").value=sessionStorage.getItem("sls-api-key")||bundledKey;
function buildUrl(){const role=roles[$("role").value],host=$("host").value.trim()||"localhost",stream=$("stream").value.trim()||"feed1";$("url").textContent=`srt://${host}:${role.port}?streamid=${role.id}${encodeURIComponent(stream)}`}
function number(value,suffix=""){return typeof value==="number"?`${value.toFixed(2)}${suffix}`:"-"}function escapeHtml(text){const span=document.createElement("span");span.textContent=text;return span.innerHTML}
function streamKey(){const stream=$("monitorStream").value.trim()||"feed1";return stream.includes("/")?stream:`publish/live/${stream}`}
function previewUrl(){const role=roles[$("monitorRole").value],key=streamKey().split("/").map(encodeURIComponent).join("/");return `/media/${role.port}/${key}/live.m3u8`}
function loadPreview(){const video=$("video"),url=previewUrl();$("previewMessage").textContent=`Loading ${url}`;if(hls){hls.destroy();hls=null}if(video.canPlayType("application/vnd.apple.mpegurl")){video.src=url;video.play().catch(()=>{})}else if(window.Hls&&Hls.isSupported()){hls=new Hls({liveSyncDurationCount:2});hls.loadSource(url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{video.play().catch(()=>{});$("previewMessage").textContent="Preview connected. Playback includes audio."});hls.on(Hls.Events.ERROR,(_,event)=>{if(event.fatal)$("previewMessage").textContent="Preview is not ready. Confirm the publisher type and wait for HLS segments."})}else{$("previewMessage").textContent="This browser cannot play HLS preview media."}}
function push(values){Object.entries(values).forEach(([key,value])=>{history[key].push(typeof value==="number"?value:0);if(history[key].length>30)history[key].shift()});drawCharts()}
function draw(canvasId,series){const canvas=$(canvasId),rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=104*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=rect.width,h=104,all=series.flatMap(s=>s.values),max=Math.max(1,...all);ctx.strokeStyle="#203846";ctx.beginPath();ctx.moveTo(0,h-1);ctx.lineTo(w,h-1);ctx.stroke();series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.beginPath();s.values.forEach((v,i)=>{const x=(i/Math.max(29,s.values.length-1))*w,y=h-8-(v/max)*(h-18);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function drawCharts(){draw("rateChart",[{values:history.rate,color:"#24d39a"}]);draw("rttChart",[{values:history.rtt,color:"#ffca62"}]);draw("timingChart",[{values:history.latency,color:"#24d39a"},{values:history.buffer,color:"#45a3ff"}]);draw("packetChart",[{values:history.loss,color:"#ffca62"},{values:history.drop,color:"#ff6175"}])}
async function refresh(){const headers={},key=$("key").value.trim(),endpoint=key?"/stats":`/stats?publisher=${encodeURIComponent(streamKey())}`;if(key)headers.Authorization=key;try{const response=await fetch(endpoint,{headers}),data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);$("health").textContent="Online";$("health").classList.add("live");$("message").textContent=key?"Listing all publishers; statistics update every 2 seconds.":"Monitoring the entered stream only. Add an API key to list all publishers.";const publishers=Object.entries(data.publishers||{});$("publishers").innerHTML=publishers.length?publishers.map(([stream,s])=>`<tr class="clickable" data-stream="${escapeHtml(stream)}"><td>${escapeHtml(stream)}</td><td>${number(s.latency," ms")}</td><td>${number(s.rtt," ms")}</td><td>${number(s.mbpsRecvRate," Mbps")}</td><td>${s.pktRcvLoss??"-"}</td><td>${s.pktRcvDrop??"-"}</td><td>${number(s.msRcvBuf," ms")}</td></tr>`).join(""):'<tr><td class="empty" colspan="7">No matching active publisher.</td></tr>';const selected=data.publishers[streamKey()]||publishers.find(([name])=>name.endsWith("/"+$("monitorStream").value.trim()))?.[1];if(selected)push({rate:selected.mbpsRecvRate,rtt:selected.rtt,latency:selected.latency,buffer:selected.msRcvBuf,loss:selected.pktRcvLoss,drop:selected.pktRcvDrop});document.querySelectorAll("[data-stream]").forEach(row=>row.onclick=()=>{$("monitorStream").value=row.dataset.stream.split("/").pop();loadPreview()})}catch(error){$("health").textContent="Stats locked";$("health").classList.remove("live");$("message").textContent=error.message}}
["host","role","stream"].forEach(id=>$(id).addEventListener("input",buildUrl));$("copy").addEventListener("click",async()=>navigator.clipboard.writeText($("url").textContent));$("apply").addEventListener("click",()=>{sessionStorage.setItem("sls-api-key",$("key").value.trim());refresh()});buildUrl();refresh();setInterval(refresh,2000);
$("loadPreview").addEventListener("click",loadPreview);$("snapshot").addEventListener("click",()=>{const video=$("video"),capture=$("capture");if(!video.videoWidth){$("previewMessage").textContent="Play a preview before capturing a frame.";return}capture.width=video.videoWidth;capture.height=video.videoHeight;capture.getContext("2d").drawImage(video,0,0);capture.style.display="block"});drawCharts();
</script></body></html>)HTML";

static const char *SLS_HELP_HTML = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SRT Console Help</title>
<style>:root{--bg:#071019;--panel:#101d27;--text:#e7f0f5;--muted:#9bb0bd;--accent:#24d39a;--border:#203846;--warn:#ffca62}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 Inter,"Segoe UI",Arial,sans-serif}main{width:min(980px,calc(100% - 40px));margin:0 auto;padding:36px 0 60px}a{color:var(--accent)}h1{font-size:36px;margin:0 0 8px}h2{font-size:20px;margin:28px 0 12px}p{color:var(--muted)}.top{display:flex;justify-content:space-between;align-items:center}.button{padding:9px 14px;border:1px solid var(--border);border-radius:8px;text-decoration:none;color:var(--text)}.card{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:18px;margin:12px 0}.roles{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}.roles .card{margin:0}code{color:var(--accent);font-family:ui-monospace,monospace}.warning{border-left:3px solid var(--warn)}ol li,ul li{margin:7px 0;color:var(--muted)}strong{color:var(--text)}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid var(--border);text-align:left}th{color:var(--muted)}</style></head><body><main>
<div class="top"><div><h1>Using SRT Live Server Console</h1><p>Roles, previews and connection diagnostics</p></div><a class="button" href="/">Dashboard</a></div>
<h2>Quick Start</h2><ol><li>Choose the connection role and stream name on the dashboard, then copy the generated SRT URL into the encoder or receiver.</li><li>The GUI image is configured with the local-preview stats key <code>sls-gui-dashboard-local</code>, already filled in under Stats Access, so it lists all active publishers immediately. Replace this value in <code>sls.conf</code> before making the service public.</li><li>For a publishing feed, choose its publisher type in Feed Monitor, enter the stream name, and press <strong>Load Preview</strong>. The first preview appears after HLS segments have been generated.</li></ol>
<h2>Roles</h2><div class="roles">
<div class="card"><strong>Direct publish</strong><p>Standard SRT input from OBS, FFmpeg or hardware encoders. Default port <code>4001/udp</code>; StreamID <code>publish/live/name</code>.</p></div>
<div class="card"><strong>SRTLA publish</strong><p>Bonded/mobile ingest using SRTLA receiver behavior. Default port <code>4002/udp</code>. Use this only for SRTLA sources.</p></div>
<div class="card"><strong>Playback</strong><p>SRT output consumed by a mixer, decoder or FFmpeg. Default port <code>4000/udp</code>; StreamID <code>play/live/name</code>.</p></div>
<div class="card"><strong>Studio direct publish</strong><p>Lower-latency direct-SRT input intended for controlled networks. Default port <code>30002/udp</code>.</p></div>
<div class="card"><strong>Studio playback</strong><p>Output for studio feeds received through the low-latency server. Default port <code>30003/udp</code>.</p></div></div>
<h2>Browser Preview</h2><div class="card"><p>SRT cannot play directly in browsers. This image records short MPEG-TS HLS segments for publishers and serves a live HLS playlist to the dashboard. Preview includes <strong>video and audio</strong>; Snapshot captures the visible video frame. Typical preview delay is several seconds because segments must complete before playback.</p><p>Safari plays HLS natively. Other supported browsers use <code>hls.js</code> loaded by the dashboard. The host running the browser needs access to the hls.js CDN unless that script is later packaged locally.</p></div>
<h2>Metrics</h2><table><tr><th>Metric</th><th>Meaning</th></tr><tr><td>Receive rate</td><td>Current incoming payload throughput in Mbps.</td></tr><tr><td>RTT</td><td>SRT network round-trip time; rising RTT commonly indicates path congestion or rerouting.</td></tr><tr><td>Latency</td><td>Negotiated receive delay budget for retransmission and timed delivery.</td></tr><tr><td>Receive buffer</td><td>Buffered media duration waiting at the receiver.</td></tr><tr><td>Loss / drop</td><td>Lost packets and packets ultimately dropped after recovery was not possible in time.</td></tr></table>
<h2>Synchronization</h2><div class="card warning"><p>TSBPD preserves timing inside each SRT connection and uses negotiated latency to schedule packet delivery. It does not align independent cameras to the same video frame. For frame-synchronized production, sources must use shared timing/timecode or the mixer must add measured alignment delay.</p></div>
<h2>Security And Storage</h2><ul><li>The bundled key <code>sls-gui-dashboard-local</code> is included for a local/LAN preview and is visible in this public image. It is not a security boundary. Replace it in <code>sls.conf</code> for an external deployment.</li><li>The dashboard stores the currently selected statistics key in browser session storage and sends it in the <code>Authorization</code> header.</li><li>HLS preview segments are written beneath <code>/tmp/mov/sls</code> in the container. Long-running streams consume storage until a retention policy is added or the container is recreated.</li><li>Do not expose the dashboard or preview endpoint publicly without authentication and TLS in front of it.</li></ul>
</main></body></html>)HTML";
